package net.runelite.client.plugins.agilityPlusV2.steps;

public enum CanfisSteps {
    NONE,
    CANFIS_FAIL,
    CANFIS_START,
    CANFIS_BUSH,
    CANFIS_FIRST_ROOF_MOG,
    CANFIS_FIRST_ROOF_NO_MOG,
    CANFIS_GRACEFULMARK1,
    CANFIS_SECOND_ROOF_MOG,
    CANFIS_SECOND_ROOF_NO_MOG,
    CANFIS_GRACEFULMARK2,
    CANFIS_THIRD_ROOF_MOG,
    CANFIS_THIRD_ROOF_NO_MOG,
    CANFIS_GRACEFULMARK3,
    CANFIS_FOURTH_ROOF_MOG,
    CANFIS_FOURTH_ROOF_NO_MOG,
    CANFIS_GRACEFULMARK4,
    CANFIS_FIFTH_ROOF_MOG,
    CANFIS_FIFTH_ROOF_NO_MOG,
    CANFIS_GRACEFULMARK5,
    CANFIS_SIXTH_ROOF,
    CANFIS_SEVENTH_ROOF
}
