name: "Sync with original repo - action"
#https://github.com/marketplace/actions/fork-sync

on:
  schedule:
    - cron: '0 16 * * 1,4'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          owner: runelite
          head: master
          base: master
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true