name: "Sync Fork"
#https://github.com/marketplace/actions/fork-sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: runelite
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          auto_approve: true
